export const sagaActions = {
  LOAD_POKEMON_SAGA: "LOAD_POKEMON_SAGA",
  LOAD_POKEMON_SUCCEEDED_SAGA: "LOAD_POKEMON_SUCCEEDED_SAGA",
  LOAD_POKEMON_FAILED_SAGA: "LOAD_POKEMON_FAILED_SAGA",
  SELECT_POKEMON: "SELECT_POKEMON",
  GENERIC_ERROR_SAGA: "GENERIC_ERROR_SAGA",
};
